data:
  raw_path: "data\\raw\\customer_churn_1M.csv"
  processed_folder: "data/processed/"
  target_column: "churn"

features:
  numerical_features:
    - "age"
    - "annual_income"
    - "dependents"
    - "tenure"
    - "senior_citizen"
    - "monthlycharges"
    - "totalcharges"
    - "num_services"
    - "has_phone_service"
    - "has_internet_service"
    - "has_online_security"
    - "has_online_backup"
    - "has_device_protection"
    - "has_tech_support"
    - "has_streaming_tv"
    - "has_streaming_movies"
    - "customer_satisfaction"
    - "num_complaints"
    - "num_service_calls"
    - "late_payments"
    - "avg_monthly_gb"
    - "days_since_last_interaction"
    - "credit_score"
    - "estimated_clv"
    - "charges_ratio"
    - "frustration_index"
    - "complaints_per_month"
    - "gb_per_service"
    - "account_age_days"

  categorical_features:
    - "gender"
    - "education"
    - "marital_status"
    - "contract"
    - "payment_method"
    - "paperless_billing"